version: "3.9"
services:
  fashion-segmentation:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MODEL_NAME=trained_model
    volumes:
      - ./trained_model:/models/trained_model/1
